name: example-literal-delimiter
params: params.dat
scheduler: pbs
schema:
  name: colon
  format: {delimiter: ":", header: true, id_field: id}
  fields:
    - {name: id, type: regex, pattern: "[a-z]+"}
    - {name: value, type: str, min_length: 1}
pipeline:
  stages:
    - {name: work, command: 'printf "%s:%s\n" "$JC_id" "$JC_value"'}
