"""Small read/write primitives shared by the store: atomic files, shell
fragments, and the row-lookup helpers that don't belong to any one class."""

from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Sequence

if TYPE_CHECKING:
    from .model import RowState


def _column_value(row: "RowState", column: str,
                  field_names: Optional[Sequence[str]]) -> str:
    """A row's value for a column, falling back to its raw text.

    A row that failed validation has no typed parameters, but must still be
    findable by name: locating it is the first step in correcting it.
    """
    if column in row.params:
        return str(row.params[column])
    if row.raw_fields and field_names is not None:
        try:
            position = list(field_names).index(column)
        except ValueError:
            return ""
        if position < len(row.raw_fields):
            return row.raw_fields[position].strip()
    return ""


def row_name(index: int) -> str:
    """Directory name for the nth data row, padded for stable ordering."""
    return _pad(str(index + 1))


def _pad(value: str) -> str:
    return f"{int(value):06d}"


def render_env(params: Dict[str, Any]) -> str:
    """Render parameters as a shell fragment a job can source.

    Values are single-quoted with embedded quotes escaped, so a parameter
    containing spaces or shell metacharacters reaches the job exactly as
    validated rather than being re-split by the shell.
    """
    lines = ["# Generated by jobchain. Do not edit; use 'jobchain rerun --set'.\n"]
    for key in sorted(params):
        value = params[key]
        if value is None:
            rendered = ""
        elif isinstance(value, bool):
            rendered = "1" if value else "0"
        else:
            rendered = str(value)
        lines.append(f"JC_{key}={shell_quote(rendered)}\n")
        lines.append(f"export JC_{key}\n")
    return "".join(lines)


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def _parse_handoff(text: str) -> Dict[str, str]:
    """Parse the shell fragment stages emit into a mapping."""
    values: Dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith("JC_OUT_") and "=" in line:
            key, _, raw = line.partition("=")
            name = key[len("JC_OUT_"):]
            value = raw.strip()
            if value.startswith("'") and value.endswith("'") and len(value) >= 2:
                value = value[1:-1].replace("'\\''", "'")
            values[name] = value
    return values


def _parse_assignments(text: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for line in text.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            out[key.strip()] = value.strip()
    return out


def _hostname() -> str:
    import socket
    try:
        return socket.gethostname()
    except OSError:  # pragma: no cover
        return "unknown"


def _write_text(path: str, text: str) -> None:
    """Write text atomically and clean up an abandoned temporary file."""
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    temporary = f"{path}.tmp.{os.getpid()}"
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        # If writing or replacement fails, the old target remains intact, but
        # the staging file must not become stale state or confuse recovery.
        try:
            if os.path.exists(temporary):
                os.unlink(temporary)
        except OSError:
            pass


def _write_json(path: str, payload: Any) -> None:
    _write_text(path, json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n")


def _read_text(path: str, default: str = "") -> str:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return default


def _read_json(path: str, default: Any) -> Any:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError):
        return default


def _read_optional(path: str) -> Optional[str]:
    stripped = _read_text(path, "").strip()
    return stripped or None


def _read_lines(path: str) -> List[str]:
    return [line for line in _read_text(path, "").splitlines() if line.strip()]
